### ISSUE TITLE
Configuring anaconda client requires sudo

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/runbooks#61]
```
1.6.4.2 Configure Anaconda Client 
anaconda config --set url http://<your Anaconda Server>:8080/api -s 
[admin@XXXXXXXX$ anaconda config --set url http://xxxxxxxxx.xxxxx.xxxx.hsbc:8080/api -s 
[ERROR] 
Traceback (most recent call last): 
File "/opt/wakari/anaconda/bin/anaconda", line 6, in <module> 
sys.exit(main()) 
File "/opt/wakari/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 87, in main 
description=__doc__, version=version) 
File "/opt/wakari/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main 
return args.main(args) 
File "/opt/wakari/anaconda/lib/python2.7/site-packages/binstar_client/commands/config.py", line 137, in main 
set_config(config, args.user) 
File "/opt/wakari/anaconda/lib/python2.7/site-packages/binstar_client/utils/__init__.py", line 283, in set_config 
os.makedirs(data_dir) 
File "/opt/wakari/anaconda/lib/python2.7/os.py", line 157, in makedirs 
mkdir(name, mode) 
OSError: [Errno 13] Permission denied: '/etc/xdg/binstar' 
[admin@gbl11748 root]$
```

**Comment by mrduane** [comment]
Is this always the case? 
Also, see https://github.com/ContinuumIO/runbooks/issues/67

**Comment by amccarty** [comment]
@bkreider are you saying a regular user should be able to write to /etc/xdg/binstar?
