### ISSUE TITLE
Issues with current runbook and aug archive

### ISSUE THREAD

**Issue by sandhujasmine** [ContinuumIO/runbooks#78]
1. We don't yet have anaconda-adam archive in our air gap archives. Added [issue](https://github.com/ContinuumIO/implementation_engineering/issues/41). Till these are added, we should not update the runbook. Will need to roll back to anaconda cluster instructions

2. Aug archive for win-32 packages is not indexed, see [issue](https://github.com/ContinuumIO/implementation_engineering/issues/40). [Mirroring](http://runbooks.readthedocs.io/en/latest/AnacondaRepository.html#optional-mirror-the-r-channel) the R-channel fails.

3. Need help figuring out what this [section](http://runbooks.readthedocs.io/en/latest/AnacondaRepository.html#optional-assemble-installer-resources-manually) and this [section](http://runbooks.readthedocs.io/en/latest/AnacondaRepository.html#optional-installing-from-platform-based-archives) should include. Maybe related to [#32](https://github.com/ContinuumIO/implementation_engineering/issues/32)

4. Need to understand what is required for [#32](https://github.com/ContinuumIO/implementation_engineering/issues/32)

**Comment by amccarty** [comment]
re: #3: you _shouldn't_ have to specify the platform (unless you're suggesting doing this for clarity) since these tarballs only include that particular platform.

**Comment by sandhujasmine** [comment]
> re: #3: you shouldn't have to specify the platform (unless you're suggesting doing this for clarity) since these tarballs only include that particular platform.

I tried it but it fails:

Here's the error for 'R' packages:

```
Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "/home/anaconda-server/miniconda2/bin/anaconda-server-sync-conda", line 9, in <module>
    load_entry_point('binstar-server==2.19.2', 'console_scripts', 'anaconda-server-sync-conda')()
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/scripts/sync_conda_mirror.py", line 82, in main
    index = fetch_index(tuple(channel_urls))
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 194, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 118, in fetch_repodata
    raise RuntimeError(msg)
RuntimeError: Could not find URL: file:///installer/R/pkgs/linux-32/
```

```
$ ls /installer/R/pkgs/
linux-64
```

Similarly if I remove from conda.yaml, I get following error:
```
Traceback (most recent call last):
  File "/home/anaconda-server/miniconda2/bin/anaconda-server-sync-conda", line 9, in <module>
    load_entry_point('binstar-server==2.19.2', 'console_scripts', 'anaconda-server-sync-conda')()
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/scripts/sync_conda_mirror.py", line 82, in main
    index = fetch_index(tuple(channel_urls))
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 194, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 118, in fetch_repodata
    raise RuntimeError(msg)
RuntimeError: Could not find URL: file:///installer/anaconda-suite/pkgs/linux-32/
```

anaconda-cluster works fine because it has packages for all platforms. There are some inconsistencies for the different tarballs - will document and share tomorrow.

**Comment by sandhujasmine** [comment]
Some more issues with aug platform specific archives:

1. [#42](https://github.com/ContinuumIO/implementation_engineering/issues/42)
2. [#43](https://github.com/ContinuumIO/implementation_engineering/issues/43)
